### ISSUE TITLE
initialize builder from existing struct instance

### ISSUE THREAD

**Issue by t-nil** [colin-kiegel/rust-derive-builder#290] opened 2023-06-15 08:00 UTC
Hello,

I just discovered derive_builder, and for me it seems a common use case to initialize a builder with an existing struct before modifying some fields, like the struct update syntax mentioned [here](https://doc.rust-lang.org/book/ch05-01-defining-structs.html#creating-instances-from-other-instances-with-struct-update-syntax).

E.g., is a syntax like 

``` rust
let s1: Struct = […];
// …
StructBuilder::from_struct(s1).field1(…).field2(…);
```

analogous to pure rust
```rust
let s1: Struct = […];
// …
let s2 = Struct {
field1: […],
field2: […],
..s1
}
```

already possible or planned for the future?

Thanks for your time!

PS: I am quite new to rust, maybe I am overlooking something.

**Comment by TedDriggs** [comment] 2023-06-17 01:08
Duplicate of #170

**Closed** 2023-06-17 01:08 UTC
