### ISSUE TITLE
Feature request: `impl fn builder() -> Builder` for the struct that is derived from

### ISSUE THREAD

**Issue by tonywu6** [colin-kiegel/rust-derive-builder#320] opened 2024-05-15 09:58 UTC
I have a really minor, DX-related suggestion: add a `builder` method to the struct being derived from which will return a builder instance. Something like:

```diff
  #[derive(Builder)]
  struct Lorem {
      ipsum: u32,
  }

  #[automatically_derived]
  #[derive(Clone, Default)]
  struct LoremBuilder {
      // ...
  }
  
  #[automatically_derived]
  #[allow(dead_code)]
  impl LoremBuilder {
      // ...
  }
  
+ #[automatically_derived]
+ impl Lorem {
+     pub fn builder() -> LoremBuilder {
+         LoremBuilder::default()
+     }
+ }
```

One could then use the builder like:

```rust
use Lorem;
let builder = Lorem::builder();
```

How this is different from `use LoremBuilder` is that editor features like VS Code's "Go to References" will also now track builder usage.

Otherwise, there's no `LoremBuilder` in the source file to be "clicked on", and the only way I found for looking up references to the builder is to do a textual search.

This is the derive hack I came up with:

```rust
#[proc_macro_derive(BuilderFor, attributes(builder))]
pub fn derive_builder_method(input: proc_macro::TokenStream) -> proc_macro::TokenStream {
    let input = parse_macro_input!(input as ItemStruct);

    let struct_name = input.ident;
    let generics = input.generics;

    // this is a mess
    let builder_name = input
        .attrs
        .iter()
        .find_map(|attr| {
            if !attr.path().is_ident("builder") {
                return None;
            };
            attr.parse_args_with(Punctuated::<MetaNameValue, Token![,]>::parse_terminated)
                .ok()?
                .iter()
                .find_map(|option| {
                    if !option.path.is_ident("name") {
                        return None;
                    }
                    let value: LitStr = syn::parse2(option.value.to_token_stream()).ok()?;
                    Some(Ident::new(&value.value(), value.span()))
                })
        })
        .unwrap_or(Ident::new(&format!("{}Builder", struct_name), struct_name.span()));

    quote! {
        #[automatically_derived]
        impl #generics #struct_name #generics {
            pub fn builder() -> #builder_name {
                #builder_name::default()
            }
        }
    }
    .into()
}
```

**Comment by TedDriggs** [comment] 2024-05-15 12:31
This is a duplicate of #73, which was closed for the rationale explained [here](https://github.com/colin-kiegel/rust-derive-builder/pull/265#pullrequestreview-1147489685)

I strongly endorse providing a `builder` method on the target type for your callers, for all the developer experience reasons you mentioned, in addition to making discoverability easier and `use` statements cleaner (the user just imports the struct they actually want to use, and then find builders off that). I personally add a method like this to all my builder-deriving structs.

**Closed by TedDriggs** 2024-05-15 12:31 UTC

**Comment by JKRhb** [comment] 2026-04-26 11:43
Hi @TedDriggs, sorry for bringing up this issue (or family of issues) once again, but I was wondering if the feature could be hidden via a feature flag. This way it would not mess up the documentation of people who don't use it, but it would benefit the rest.
