### ISSUE TITLE
enh: support infallible builders

### ISSUE THREAD

**Issue by rbtcollins** [colin-kiegel/rust-derive-builder#324] opened 2024-06-25 18:31 UTC
When `builder(default)` is in use, and no validation is present, the builder cannot fail - it would be nice to change the return type (probably explicitly, e.g. `builder(default, infallible)`) to reflect this, rather than having unwrap() in prod code, or colouring functions that can't otherwise fail.

**Comment by TedDriggs** [comment] 2024-07-02 12:45
Duplicate of #293

**Closed by TedDriggs** 2024-07-02 12:45 UTC
