### ISSUE TITLE
attribute support. example serde_with

### ISSUE THREAD

**Issue by GopherJ** [colin-kiegel/rust-derive-builder#165] opened 2020-05-23 14:20 UTC
```rust
// EsAlert may have duration field
#[derive(Serialize, Deserialize, Debug, Clone, Builder)]
#[builder(public, field(public), derive(Serialize, Deserialize, Debug))]
pub struct EsAlert {
    pub client_id: String,
    pub mac: String,
    pub mac_detected: String,
    pub label: String,
    pub label_detected: String,
    pub rssi: i32,
    pub distance: u32,
    #[builder(default = "0")]
    pub duration: u32,
    #[serde(with = "ts_milliseconds")]
    pub timestamp: NaiveDateTime,
    pub location: Location,
    pub source: AlertSource,
    pub alert_level: u32,
}

```

**Comment by GopherJ** [comment] 2020-05-23 14:29
I would like to be able to deserialize:

```
"[{\"alert_level\":3,\"client_id\":\"b2f2036472c6482d9fe7f2c8c63513ae\",\"distance\":97,\"duration\":0,\"label\":\"38341\",\"label_detected\":\"d581\",\"location\":{\"lat\":48.879667,\"lon\":2.328633},\"mac\":\"eb99910795c5\",\"mac_detected\":\"c493000dd36b\",\"rssi\":-80,\"source\":{\"mac\":\"c4930012dcf6\",\"type\":\"gateway\"},\"timestamp\":1590237230381},{\"alert_level\":3,\"client_id\":\"b2f2036472c6482d9fe7f2c8c63513ae\",\"distance\":97,\"duration\":9,\"label\":\"38341\",\"label_detected\":\"d581\",\"location\":{\"lat\":48.879667,\"lon\":2.328633},\"mac\":\"eb99910795c5\",\"mac_detected\":\"c493000dd36b\",\"rssi\":-80,\"source\":{\"mac\":\"c4930012dcf6\",\"type\":\"gateway\"},\"timestamp\":1590235463372},{\"alert_level\":3,\"client_id\":\"b2f2036472c6482d9fe7f2c8c63513ae\",\"distance\":97,\"duration\":0,\"label\":\"38341\",\"label_detected\":\"d581\",\"location\":{\"lat\":48.879667,\"lon\":2.328633},\"mac\":\"eb99910795c5\",\"mac_detected\":\"c493000dd36b\",\"rssi\":-80,\"source\":{\"mac\":\"c4930012dcf6\",\"type\":\"gateway\"},\"timestamp\":1590235449212},{\"alert_level\":3,\"client_id\":\"b2f2036472c6482d9fe7f2c8c63513ae\",\"distance\":97,\"duration\":10,\"label\":\"38341\",\"label_detected\":\"d581\",\"location\":{\"lat\":48.879667,\"lon\":2.328633},\"mac\":\"eb99910795c5\",\"mac_detected\":\"c493000dd36b\",\"rssi\":-80,\"source\":{\"mac\":\"c4930012dcf6\",\"type\":\"gateway\"},\"timestamp\":1590235436806},{\"alert_level\":3,\"client_id\":\"b2f2036472c6482d9fe7f2c8c63513ae\",\"distance\":97,\"duration\":13,\"label\":\"38341\",\"label_detected\":\"d581\",\"location\":{\"lat\":48.879667,\"lon\":2.328633},\"mac\":\"eb99910795c5\",\"mac_detected\":\"c493000dd36b\",\"rssi\":-80,\"source\":{\"mac\":\"c4930012dcf6\",\"type\":\"gateway\"},\"timestamp\":1590234525775},{\"alert_level\":3,\"client_id\":\"b2f2036472c6482d9fe7f2c8c63513ae\",\"distance\":97,\"duration\":0,\"label\":\"38341\",\"label_detected\":\"d581\",\"location\":{\"lat\":48.879667,\"lon\":2.328633},\"mac\":\"eb99910795c5\",\"mac_detected\":\"c493000dd36b\",\"rssi\":-80,\"source\":{\"mac\":\"c4930012dcf6\",\"type\":\"gateway\"},\"timestamp\":1590234485252}]"
```
to `Vec<EsAlertBuilder>` but seems  since `EsAlertBuilder` doesn't have attribute ` #[serde(with = "ts_milliseconds")]` this cannot be done

**Comment by TedDriggs** [comment] 2020-05-27 17:13
This is a duplicate of #90 - please add your use-case to that issue.

**Closed by TedDriggs** 2020-05-27 17:13 UTC
