### ISSUE TITLE
Testing fails due to unused macro definitions

### ISSUE THREAD

**Issue by TedDriggs** [colin-kiegel/rust-derive-builder#100] opened 2017-05-30 20:48 UTC
Attempt to run `cargo test` from `./derive_builder`

**Expected:** Tests run and pass
**Observed:** Compilation fails

```
error: unused macro definition
 --> /Users/ehd/rust/rust-derive-builder/derive_builder_core/src/log_disabled.rs:5:1
  |
5 | / macro_rules! log_enabled {
6 | |     ($( $x:tt )*) => { false }
7 | | }
  | |_^
  |
  = note: #[deny(unused_macros)] implied by #[deny(warnings)]
note: lint level defined here
 --> /Users/ehd/rust/rust-derive-builder/derive_builder_core/src/lib.rs:25:9
  |
25| #![deny(warnings, missing_docs)]
  |         ^^^^^^^^
```

**Comment by colin-kiegel** [comment] 2017-05-31 01:05
Ok, thx for the report. Note, I am still traveling.

That seems to be a regression due to changes in newer Rust versions, right?

We probably need to add `#![allow(unused_macros)]` in the rust file which defines this mock facade.

**Comment by colin-kiegel** [comment] 2017-06-30 09:09
ok, fixed in https://github.com/colin-kiegel/rust-derive-builder/commit/7d1188937b0c3887ae56e7188e74821d00c455f3.

However the build still fails due to another unrelated problem in the `compiletests` crate. It looks like a fix is on the way https://github.com/laumann/compiletest-rs/pull/68.

**Closed by colin-kiegel** 2017-06-30 09:09 UTC
